export interface Homestay {
	id: string | null
	name: string | null
	listing_url: string | null
	summary: string | null
	space: string | null
	neighborhood_overview: string | null
	notes: string | null
	transit: string | null
	access: string | null
	house_rules: string | null
	thumbnail_url: string | null
	host_id: string | null
	street: string | null
	city: string | null
	market: string | null
	smart_location: string | null
	country: string | null
	latitude: string | null
	longitude: string | null
	room_type: string | null
	bathrooms: number | null
	accommodates: number | null
	bedrooms: number | null
	beds: number | null
	bed_type: string | null
	amenities: string[] | null
	price: number | null
	weekly_price: number | null
	extra_people: number | null
	minimum_nights: number | null
	maximum_nights: number | null
	review_scores_rating: number | null
}
